### PR TITLE
Add instructions for extending an LVM volume

### PR DESCRIPTION
**Pull request by wehimwich**
Seeded from [FSL10 Issue #28](https://github.com/nvi-inc/fsl10/pull/28).

This is a try at documenting a procedure for extending an LVM volume. It is a little cumbersome, but that is partly to make it safe for users. Perhaps it should be generalized a little bit to handle reducing a volume as well. Although I am not too eager to add that.

### CODE REVIEW

**Comment by wehimwich** [comment]
The draft _.html_ can't be attached directly. The link [Increase the size of an LVM volume](https://nvi-inc.github.io/fsl11/draft_lvm-extend.html#_increase_the_size_of_an_lvm_volume) will take you directly to the relevant section of the draft document (please note that other sections are still for FSL10). The link is out-of-date now.

**Comment by wehimwich** [comment]
@jfhquick had commented:

My first comment is that 'resize2fs' is inherently dangerous in that it cannot be interrupted (as I found out to my sorrow).  Fortunately it is pretty quick if you are enlarging a filesystem.  If you do was to shrink a partition, then it must be unmounted and your method will fail.

I also don't think this fits that well in appendix A.  It's more of a maintenance task and closer to Appendix C or even B.
 
Corrections:
line 1718, your use of 'Path' is confusing (since we're talking of _Path_) so I'd leave that out.
line 1799, this needs a warning e.g., 'Do Not INTERRUPT'.

**Comment by wehimwich** [comment]
> My first comment is that 'resize2fs' is inherently dangerous in that it cannot be interrupted (as I found out to my sorrow). Fortunately it is pretty quick if you are enlarging a filesystem. If you do was to shrink a partition, then it must be unmounted and your method will fail.

Would it better to unmount for an increase as well? Perhaps I had not unmounted when I used this procedure because the volume was in use. Can't remember now.

I had not intended to get into shrinking, having no experience. If the process can be easily generalized and some one is willing to sign off on it, we could. 

For those using a RAID, the recoverable testing procedure makes it much easier to recover if there is a problem.

> I also don't think this fits that well in appendix A. It's more of a maintenance task and closer to Appendix C or even B.

Fair enough. We could make a new appendix (B?) for maintenance activities. I looked over  the current Appendix A briefly. It looked the sub-section for updating the IP address, hostname, etc. might be a better fit for the maintenance appendix as well. Maybe managing security update should be part of that appendix too. OTOH, maybe security updates are importtant enough and there is enough content that it should stand on its own.

> line 1718, your use of 'Path' is confusing (since we're talking of _Path_) so I'd leave that out.

This is one of those things were it is intuitively obvious what is going on, but is cumbersome to explain in step-by-step instructions. In this case, it looks like it should have been _Path_. I would propose to fix that, but also reword the clause so the there is more separation between the two different unusual fonts.


> line 1799, this needs a warning e.g., 'Do Not INTERRUPT'.

Sounds good

**Comment by wehimwich** [comment]
The draft document section at [Increase the size of an LVM volume](https://nvi-inc.github.io/fsl11/draft_lvm-extend.html#_increase_the_size_of_an_lvm_volume) is also updated. The link is out-of-date now.

**Comment by jfhquick** [comment]
> > My first comment is that 'resize2fs' is inherently dangerous in that it cannot be interrupted (as I found out to my sorrow). Fortunately it is pretty quick if you are enlarging a filesystem. If you do was to shrink a partition, then it must be unmounted and your method will fail.
> 
> Would it better to unmount for an increase as well? Perhaps I had not unmounted when I used this procedure because the volume was in use. Can't remember now.

No, that's not necessary and yes, it's often hard to achieve.

> I had not intended to get into shrinking, having no experience. If the process can be easily generalized and some one is willing to sign off on it, we could.

Better not to mention it as it's got too many nasty pitfalls for the unwary.

> > I also don't think this fits that well in appendix A. It's more of a maintenance task and closer to Appendix C or even B.
> 
> Fair enough. We could make a new appendix (B?) for maintenance activities. I looked over the current Appendix A briefly. It looked the sub-section for updating the IP address, hostname, etc. might be a better fit for the maintenance appendix as well. Maybe managing security update should be part of that appendix too. OTOH, maybe security updates are important enough and there is enough content that it should stand on its own.

So I agree with you analysis and would make a new appendix C. **Other maintenance activities** to contain this and the other sub-sections you identified..
 
> > line 1718, your use of 'Path' is confusing (since we're talking of _Path_) so I'd leave that out.
> 
> This is one of those things were it is intuitively obvious what is going on, but is cumbersome to explain in step-by-step instructions. In this case, it looks like it should have been _Path_. I would propose to fix that, but also reword the clause so the there is more separation between the two different unusual fonts.

Still pending then.

> > line 1799, this needs a warning e.g., 'Do Not INTERRUPT'.
> 
> Sounds good

And looks good too :)

**Comment by wehimwich** [comment]
The draft document section at [Increase the size of an LVM volume](https://nvi-inc.github.io/fsl11/draft_lvm-extend.html#_increase_the_size_of_an_lvm_volume) has been updated. It was improved and rebased on to the latest documents, placing the new section at the end of Appendix B.

**Review by jfhquick — APPROVED** [review]
I added a few minor tweaks, This is now good to go.

**Pull request merged**
